from dash import dcc, html


def get_layout(df):
    # Harvest unique store types to feed dynamic demographic selector menu
    unique_stores = df["Store_type"].dropna().unique()
    default_store = unique_stores if len(unique_stores) > 0 else None

    layout = html.Div(
        [
            html.H1("Sales Channels Analytics", style={"text-align": "center"}),
            # Section A: Chronological Weekday performance tracking chart
            html.Div(
                [
                    html.H3(
                        "Total Revenue Generated by Weekday and Store Type",
                        style={"text-align": "center"},
                    ),
                    dcc.Graph(id="channels-weekday-graph"),
                ],
                style={"margin-bottom": "40px"},
            ),
            html.Hr(),  # Separator line between sections
            # Section B: Selected Store Type Customer Demographics Overview
            html.Div(
                [
                    html.H3(
                        "Target Audience Demographic Profile Evaluation",
                        style={"text-align": "center"},
                    ),
                    html.Div(
                        [
                            html.Label("Select Sales Channel to Inspect:"),
                            dcc.Dropdown(
                                id="store_dropdown",
                                options=[
                                    {"label": store, "value": store}
                                    for store in unique_stores
                                ],
                                value=default_store,
                                style={"width": "300px", "margin": "auto"},
                            ),
                        ],
                        style={"text-align": "center", "margin-bottom": "20px"},
                    ),
                    # Two columns tracking gender bar and age distribution donut
                    html.Div(
                        [
                            html.Div(
                                [dcc.Graph(id="channels-gender-graph")],
                                style={"width": "50%"},
                            ),
                            html.Div(
                                [dcc.Graph(id="channels-age-graph")],
                                style={"width": "50%"},
                            ),
                        ],
                        style={"display": "flex"},
                    ),
                ]
            ),
        ]
    )
    return layout
